# Generated by Django 2.1.7 on 2020-07-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainNo', models.IntegerField()),
                ('travelTime', models.IntegerField()),
                ('startTime', models.CharField(max_length=4)),
                ('endTime', models.CharField(max_length=4)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='railways.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='railways.city')),
                ('travelDays', models.ManyToManyField(to='railways.days')),
            ],
        ),
    ]
