# Generated by Django 2.1.7 on 2020-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0004_passenger_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='trainNo',
            field=models.ManyToManyField(to='railways.trains'),
        ),
    ]
