# Generated by Django 2.1.7 on 2020-07-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0007_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default='Date', max_length=15),
        ),
    ]
