# Generated by Django 2.1.7 on 2020-07-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0008_auto_20200717_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='trainNo',
            field=models.ManyToManyField(to='railways.booking'),
        ),
    ]
