# Generated by Django 2.1.7 on 2020-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0009_auto_20200718_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='trainNo',
            new_name='train',
        ),
    ]
