# Generated by Django 2.1.7 on 2020-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0010_auto_20200718_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat',
            field=models.CharField(default='SL-B6', max_length=6),
        ),
    ]
