# Generated by Django 2.1.7 on 2020-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0012_auto_20200718_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='cost',
            field=models.IntegerField(default=3200),
        ),
    ]
